version: '3.2'

services:
  api-test-end2end:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    command: >
      bash -c "set -x;
               cd /opt/api;
               pip install -r ./requirements.txt;
               python -m nltk.downloader punkt stopwords;
               while true; do python app.py; done;"
    container_name: ${APP_NAME}-api-test-end2end
    depends_on:
      - postgres-test-end2end
    environment:
      - APP_NAME=$APP_NAME
      - BUZZSUMO_API_KEY=$BUZZSUMO_API_KEY
      - COMMAND_NAME=$COMMAND_NAME
      - ENV=${ENV:-end2end}
      - GIT_TAG=$GIT_TAG
      - OBJECT_STORAGE_URL=$OBJECT_STORAGE_URL
      - POSTGRES_URL=postgresql://${DB_NAME}_user:${DB_NAME}_password@postgres-end2end/${DB_NAME}
      - SCREEN_SHOT_MACHINE_KEY=$SCREEN_SHOT_MACHINE_KEY
      - TLD=$TLD
    networks:
      - db_test-end2end_nw
      - web_test-end2end_nw
    volumes:
      - ./api:/opt/api

  frontend-test-end2end:
    build:
      context: ./${FRONTEND_NAME}
      dockerfile: ./Dockerfile
    command: >
      bash -c "set -x;
               source ~/.profile;
               ln -sf /lib/node/node_modules /opt/frontend/node_modules;
               cd /opt/frontend;
               yarn start;"
    container_name: ${APP_NAME}-frontend-test-end2end
    depends_on:
      - api-test-end2end
    environment:
      - ENV=${ENV:-development}
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
      - GIT_TAG=${GIT_TAG}
    networks:
      - db_test-end2end_nw
      - web_test-end2end_nw
    ports:
      - ${FRONTEND_PORT:-3000}:3000
    volumes:
      - ./${FRONTEND_NAME}:/opt/frontend

  nginx-test-end2end:
    build:
      args:
        - MODE=test-end2end
      context: ./nginx
      dockerfile: ./Dockerfile.nossl
    container_name: ${APP_NAME}-nginx-test-end2end
    depends_on:
      - api-test-end2end
    networks:
      - web_test-end2end_nw
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  postgres-test-end2end:
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_min_duration_statement=0 -c log_statement=all -c log_duration=on
    container_name: ${APP_NAME}-postgres-test-end2end
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_NAME}_password
      - POSTGRES_USER=${DB_NAME}_user
    image: postgres:10.1
    networks:
      - db_test-end2end_nw
    volumes:
      - "./docker_data_test-end2end/postgres:/var/lib/postgresql/data"

networks:
  db_test-end2end_nw:
    driver: bridge
  web_test-end2end_nw:
    driver: bridge

volumes:
  docker_data_test-end2end:
