# Python CircleCI 2.0 configuration file
version: 2
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/{{$ORGANIZATION_NAME}}-api-ci
    docker:
      - image: circleci/python:3.7.0 # ...with this image as the primary container; this is where all `steps` will run
        environment:
          POSTGRES_URL: postgresql://$DB_NAME_user:$DB_NAME_password@localhost:5432/$DB_NAME
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_DB: $DB_NAME
          POSTGRES_PASSWORD: $DB_NAME_password
          POSTGRES_USER: $DB_NAME_user
    steps:
      - checkout # special step to check out source code to the working directory
      - restore_cache: # restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: # install and activate virtual environment with pip
          name: Install requirements
          command: |
            cd api
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python ./utils/nltk_downloader.py
      - save_cache: # special step to save dependency cache
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running flask
          command: |
            cd api
            . venv/bin/activate
            python app.py
          background: true
      - run: # run tests
          name: Running tests
          command: |
            cd api
            . venv/bin/activate
            pytest tests

  check-dependencies:
    working_directory: ~/$ORGANIZATION_NAME-api-ci # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/python:3.7.0
    steps: # a collection of executable commands
      - checkout # special step to check out source code to the working directory
      - restore_cache: # restores saved dependency cache if the Branch key template or requirements.txt files have not changed since the previous run
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: # install and activate virtual environment with pip
          name: Install requirements
          command: |
            cd api
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Check outdated dependencies
          command:
            cd api
            ./scripts/check-pip-dependencies.sh

workflows:
  version: 2
  commit:
    jobs:
      - build
  schedule:
    triggers: #use the triggers key to indicate a scheduled build
      - schedule:
          cron: "0 1 * * 1" # run every monday at 1 am !!!! UTC TIME !!!!
          filters:
            branches:
              only:
                - master
    jobs:
      - check-dependencies
